#!/bin/bash
# Link dotfiles to ~/.config

set -e

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log() { echo -e "${GREEN}[+]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }

link() {
    local src="$1"
    local dest="$2"

    mkdir -p "$(dirname "$dest")"

    if [[ -L "$dest" ]]; then
        rm "$dest"
    elif [[ -f "$dest" ]]; then
        mv "$dest" "$dest.backup"
        warn "Backed up: $dest"
    fi

    ln -sf "$src" "$dest"
    log "Linked: $dest"
}

echo "Linking dotfiles from $DOTFILES_DIR"
echo ""

# Hyprland
link "$DOTFILES_DIR/hypr/hyprland.conf" "$HOME/.config/hypr/hyprland.conf"
link "$DOTFILES_DIR/hypr/hyprlock.conf" "$HOME/.config/hypr/hyprlock.conf"
link "$DOTFILES_DIR/hypr/hyprpaper.conf" "$HOME/.config/hypr/hyprpaper.conf"

# Create local.conf if missing (machine-specific, not a symlink)
if [[ ! -f "$HOME/.config/hypr/local.conf" ]]; then
    cp "$DOTFILES_DIR/hypr/local.conf.example" "$HOME/.config/hypr/local.conf"
    log "Created: ~/.config/hypr/local.conf (edit for your monitor/GPU)"
fi

# Create empty colors.conf if missing (wallust will populate it)
if [[ ! -f "$HOME/.config/hypr/colors.conf" ]]; then
    touch "$HOME/.config/hypr/colors.conf"
    log "Created: ~/.config/hypr/colors.conf (run apply-theme to populate)"
fi

# Kitty
link "$DOTFILES_DIR/kitty/kitty.conf" "$HOME/.config/kitty/kitty.conf"

# Create empty colors.conf for kitty if missing
if [[ ! -f "$HOME/.config/kitty/colors.conf" ]]; then
    touch "$HOME/.config/kitty/colors.conf"
fi

# Fish
link "$DOTFILES_DIR/fish/config.fish" "$HOME/.config/fish/config.fish"
[[ -f "$DOTFILES_DIR/fish/fish_plugins" ]] && link "$DOTFILES_DIR/fish/fish_plugins" "$HOME/.config/fish/fish_plugins"

for f in "$DOTFILES_DIR/fish/functions/"*.fish; do
    [[ -f "$f" ]] && link "$f" "$HOME/.config/fish/functions/$(basename "$f")"
done

for f in "$DOTFILES_DIR/fish/completions/"*.fish; do
    [[ -f "$f" ]] && link "$f" "$HOME/.config/fish/completions/$(basename "$f")"
done

for f in "$DOTFILES_DIR/fish/conf.d/"*.fish; do
    [[ -f "$f" ]] && link "$f" "$HOME/.config/fish/conf.d/$(basename "$f")"
done

# Tmux
link "$DOTFILES_DIR/tmux/tmux.conf" "$HOME/.config/tmux/tmux.conf"

# Create empty colors.conf for tmux if missing
if [[ ! -f "$HOME/.config/tmux/colors.conf" ]]; then
    touch "$HOME/.config/tmux/colors.conf"
fi

# Waybar
link "$DOTFILES_DIR/waybar/config.jsonc" "$HOME/.config/waybar/config.jsonc"
link "$DOTFILES_DIR/waybar/style.css" "$HOME/.config/waybar/style.css"

# Create empty colors.css for waybar if missing
if [[ ! -f "$HOME/.config/waybar/colors.css" ]]; then
    echo "/* Generated by wallust - run apply-theme */" > "$HOME/.config/waybar/colors.css"
fi

# Rofi
link "$DOTFILES_DIR/rofi/config.rasi" "$HOME/.config/rofi/config.rasi"

# Create empty colors.rasi for rofi if missing
if [[ ! -f "$HOME/.config/rofi/colors.rasi" ]]; then
    echo "/* Generated by wallust - run apply-theme */" > "$HOME/.config/rofi/colors.rasi"
fi

# Neovim
link "$DOTFILES_DIR/nvim/init.lua" "$HOME/.config/nvim/init.lua"
mkdir -p "$HOME/.config/nvim/lua/plugins"
for f in "$DOTFILES_DIR/nvim/lua/plugins/"*.lua; do
    [[ -f "$f" ]] && link "$f" "$HOME/.config/nvim/lua/plugins/$(basename "$f")"
done

# Wallust
link "$DOTFILES_DIR/wallust/wallust.toml" "$HOME/.config/wallust/wallust.toml"
mkdir -p "$HOME/.config/wallust/templates"
for f in "$DOTFILES_DIR/wallust/templates/"*; do
    [[ -f "$f" ]] && link "$f" "$HOME/.config/wallust/templates/$(basename "$f")"
done

# Wallpapers
for f in "$DOTFILES_DIR/wallpapers/"*; do
    [[ -f "$f" ]] && link "$f" "$HOME/.config/wallpapers/$(basename "$f")"
done

# Scripts
link "$DOTFILES_DIR/scripts/apply-theme.sh" "$HOME/.local/bin/apply-theme"
link "$DOTFILES_DIR/scripts/reload-theme.sh" "$HOME/.local/bin/reload-theme"
chmod +x "$HOME/.local/bin/apply-theme"
chmod +x "$HOME/.local/bin/reload-theme"

echo ""
echo -e "${GREEN}Done!${NC} Configs linked to ~/.config"

# Apply theme if wallust is installed and wallpaper exists
if command -v wallust &> /dev/null; then
    echo ""
    WALLPAPER="${WALLPAPER:-$HOME/.config/wallpapers/one.jpg}"
    if [[ -f "$WALLPAPER" ]]; then
        echo "Applying theme from wallpaper..."
        apply-theme "$WALLPAPER"
    else
        echo -e "${YELLOW}[!]${NC} No wallpaper found at $WALLPAPER"
        echo "    Run 'apply-theme /path/to/wallpaper.jpg' to generate theme"
    fi
else
    echo ""
    echo -e "${YELLOW}[!]${NC} wallust not installed - skipping theme generation"
    echo "    Install: cargo install wallust"
fi
