# Fish shell colors - Generated by wallust

# Base colors
set -g theme_bg '{{background | strip}}'
set -g theme_fg '{{foreground | strip}}'

# Standard 16 colors
set -g theme_color0 '{{color0 | strip}}'
set -g theme_color1 '{{color1 | strip}}'
set -g theme_color2 '{{color2 | strip}}'
set -g theme_color3 '{{color3 | strip}}'
set -g theme_color4 '{{color4 | strip}}'
set -g theme_color5 '{{color5 | strip}}'
set -g theme_color6 '{{color6 | strip}}'
set -g theme_color7 '{{color7 | strip}}'
set -g theme_color8 '{{color8 | strip}}'
set -g theme_color9 '{{color9 | strip}}'
set -g theme_color10 '{{color10 | strip}}'
set -g theme_color11 '{{color11 | strip}}'
set -g theme_color12 '{{color12 | strip}}'
set -g theme_color13 '{{color13 | strip}}'
set -g theme_color14 '{{color14 | strip}}'
set -g theme_color15 '{{color15 | strip}}'

# Fish syntax highlighting
set -g fish_color_normal '{{foreground | strip}}'
set -g fish_color_command '{{color4 | strip}}'
set -g fish_color_keyword '{{color5 | strip}}'
set -g fish_color_quote '{{color2 | strip}}'
set -g fish_color_redirection '{{color6 | strip}}'
set -g fish_color_end '{{color5 | strip}}'
set -g fish_color_error ff0000
set -g fish_color_param '{{foreground | strip}}'
set -g fish_color_comment '{{color8 | strip}}'
set -g fish_color_selection --background='{{color8 | strip}}'
set -g fish_color_search_match --background='{{color8 | strip}}'
set -g fish_color_operator '{{color6 | strip}}'
set -g fish_color_escape '{{color5 | strip}}'
set -g fish_color_autosuggestion '{{color8 | strip}}'
set -g fish_color_valid_path --underline

# Pager colors
set -g fish_pager_color_progress '{{color8 | strip}}'
set -g fish_pager_color_prefix '{{color6 | strip}}'
set -g fish_pager_color_completion '{{foreground | strip}}'
set -g fish_pager_color_description '{{color8 | strip}}'

# Semantic aliases for prompt
set -g c_directory '{{color6 | strip}}'
set -g c_git_branch '{{color5 | strip}}'
set -g c_git_staged '{{color2 | strip}}'
set -g c_git_modified '{{color3 | strip}}'
set -g c_git_untracked '{{color8 | strip}}'
set -g c_git_conflict '{{color1 | strip}}'
set -g c_git_ahead '{{color6 | strip}}'
set -g c_git_behind '{{color1 | strip}}'
set -g c_git_clean '{{color2 | strip}}'
set -g c_git_op '{{color1 | strip}}'
set -g c_git_tag '{{color4 | strip}}'
set -g c_dim '{{color8 | strip}}'
set -g c_prompt '{{color5 | strip}}'
set -g c_prompt_error '{{color1 | strip}}'
set -g c_ssh '{{color3 | strip}}'
set -g c_k8s '{{color4 | strip}}'
set -g c_venv '{{color3 | strip}}'
set -g c_node '{{color2 | strip}}'
set -g c_aws '{{color3 | strip}}'
set -g c_jobs '{{color5 | strip}}'
