-- Neovim colors - Generated by wallust
-- Source this file to apply theme: :source ~/.config/nvim/colors.lua

local colors = {
    bg = "{{background}}",
    fg = "{{foreground}}",
    color0 = "{{color0}}",
    color1 = "{{color1}}",
    color2 = "{{color2}}",
    color3 = "{{color3}}",
    color4 = "{{color4}}",
    color5 = "{{color5}}",
    color6 = "{{color6}}",
    color7 = "{{color7}}",
    color8 = "{{color8}}",
    color9 = "{{color9}}",
    color10 = "{{color10}}",
    color11 = "{{color11}}",
    color12 = "{{color12}}",
    color13 = "{{color13}}",
    color14 = "{{color14}}",
    color15 = "{{color15}}",
}

-- Apply highlight groups
local set_hl = vim.api.nvim_set_hl

-- UI elements
set_hl(0, "Normal", { fg = colors.fg, bg = "NONE" })
set_hl(0, "NormalFloat", { fg = colors.fg, bg = colors.color0 })
set_hl(0, "FloatBorder", { fg = colors.color8, bg = "NONE" })
set_hl(0, "CursorLine", { bg = colors.color0 })
set_hl(0, "CursorLineNr", { fg = colors.color5, bold = true })
set_hl(0, "LineNr", { fg = colors.color8 })
set_hl(0, "SignColumn", { bg = "NONE" })
set_hl(0, "VertSplit", { fg = colors.color8 })
set_hl(0, "StatusLine", { fg = colors.fg, bg = colors.color0 })
set_hl(0, "StatusLineNC", { fg = colors.color8, bg = colors.color0 })
set_hl(0, "Pmenu", { fg = colors.fg, bg = colors.color0 })
set_hl(0, "PmenuSel", { fg = colors.bg, bg = colors.color4 })
set_hl(0, "Visual", { bg = colors.color8 })
set_hl(0, "Search", { fg = colors.bg, bg = colors.color3 })
set_hl(0, "IncSearch", { fg = colors.bg, bg = colors.color5 })

-- Syntax
set_hl(0, "Comment", { fg = colors.color8, italic = true })
set_hl(0, "Constant", { fg = colors.color3 })
set_hl(0, "String", { fg = colors.color2 })
set_hl(0, "Character", { fg = colors.color2 })
set_hl(0, "Number", { fg = colors.color3 })
set_hl(0, "Boolean", { fg = colors.color3 })
set_hl(0, "Identifier", { fg = colors.color6 })
set_hl(0, "Function", { fg = colors.color4 })
set_hl(0, "Statement", { fg = colors.color5 })
set_hl(0, "Keyword", { fg = colors.color5 })
set_hl(0, "Operator", { fg = colors.fg })
set_hl(0, "PreProc", { fg = colors.color5 })
set_hl(0, "Type", { fg = colors.color6 })
set_hl(0, "Special", { fg = colors.color1 })
set_hl(0, "Error", { fg = colors.color1 })
set_hl(0, "Todo", { fg = colors.color3, bold = true })

-- Diagnostics
set_hl(0, "DiagnosticError", { fg = colors.color1 })
set_hl(0, "DiagnosticWarn", { fg = colors.color3 })
set_hl(0, "DiagnosticInfo", { fg = colors.color4 })
set_hl(0, "DiagnosticHint", { fg = colors.color6 })

-- Git signs
set_hl(0, "GitSignsAdd", { fg = colors.color2 })
set_hl(0, "GitSignsChange", { fg = colors.color3 })
set_hl(0, "GitSignsDelete", { fg = colors.color1 })

-- Diff
set_hl(0, "DiffAdd", { bg = colors.color2, fg = colors.bg })
set_hl(0, "DiffChange", { bg = colors.color3, fg = colors.bg })
set_hl(0, "DiffDelete", { bg = colors.color1, fg = colors.bg })
set_hl(0, "DiffText", { bg = colors.color4, fg = colors.bg })

-- Telescope (if installed)
set_hl(0, "TelescopeBorder", { fg = colors.color8 })
set_hl(0, "TelescopePromptBorder", { fg = colors.color5 })
set_hl(0, "TelescopeResultsBorder", { fg = colors.color8 })
set_hl(0, "TelescopePreviewBorder", { fg = colors.color8 })
set_hl(0, "TelescopeSelection", { bg = colors.color0 })
set_hl(0, "TelescopeMatching", { fg = colors.color5, bold = true })

return colors
