#!/bin/bash
# Apply wallpaper-based theme to all applications

set -e

WALLPAPER="${1:-$HOME/.config/wallpapers/wallpaper.jpeg}"

if [[ ! -f "$WALLPAPER" ]]; then
    echo "Error: Wallpaper not found: $WALLPAPER"
    echo ""
    echo "Usage: apply-theme /path/to/wallpaper.jpg"
    echo ""
    echo "Available wallpapers:"
    ls -1 ~/.config/wallpapers/ 2>/dev/null | sed 's/^/  /'
    exit 1
fi

# Convert to absolute path
WALLPAPER="$(realpath "$WALLPAPER")"

echo "Applying theme from: $WALLPAPER"

# Get all monitors from hyprctl
MONITORS=$(hyprctl monitors -j 2>/dev/null | jq -r '.[].name' 2>/dev/null || echo "")

# Update hyprpaper config
HYPRPAPER_CONF="$HOME/.config/hypr/hyprpaper.conf"
{
    echo "# Hyprpaper - Wallpaper config"
    echo "# Generated by apply-theme"
    echo ""
    if [[ -n "$MONITORS" ]]; then
        # Set wallpaper for each monitor explicitly
        for monitor in $MONITORS; do
            echo "wallpaper {"
            echo "    monitor = $monitor"
            echo "    path = $WALLPAPER"
            echo "    fit_mode = cover"
            echo "}"
            echo ""
        done
    else
        # Fallback to all monitors
        echo "wallpaper {"
        echo "    path = $WALLPAPER"
        echo "    fit_mode = cover"
        echo "}"
    fi
} > "$HYPRPAPER_CONF"
echo "  Hyprpaper config updated"

# Reload hyprpaper
if pgrep -x hyprpaper > /dev/null; then
    pkill -x hyprpaper
    sleep 0.3
fi
hyprpaper &> /dev/null &
disown
echo "  Hyprpaper restarted"

# Extract colors and generate configs
echo "  Extracting colors..."
wallust run "$WALLPAPER"

# Reload all applications
reload-theme
